# -*- coding: utf-8 -*-
"""rvest_substack_scraping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vKIA1ZtrxkE1g9W12joFuicz8zng3-D
"""

install.packages("polite")
library(polite)

library(tidyverse)
library(rvest)
library(httr2)
library(jsonlite)

library(dplyr)

install.packages("RCurl")

library(RCurl)

#change this workflow
plumpitsjson <- read_json('plumpits.json', simplifyVector = TRUE)

#this removes most of the html garbage

plumpits <- plumpitsjson |>
  mutate(
    p_text = map_chr(
      raw_article,
      ~ read_html(.x) |>
          html_elements("p") |>
          html_text2() |>
          str_c(collapse = " ")
    )
  )

#add a feature for publication year
library(lubridate)

plumpits |> glimpse()

plumpits <- plumpits |> mutate(year_published = year(published_at)) |> select(-subtitle, -url, -author_url, -body)

plumpits$p_text[1]

#remove emojis, remove \n

substack_uncleaned <- bind_rows()